### ISSUE TITLE
Add missing fields for podTemplate.spec

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#107]
as part of https://github.com/aenix-io/etcd-operator/issues/109

```yaml
spec:
  podTemplate:
    spec:
      serviceAccountName: default
      imagePullSecrets:
      readinessGates: [] # core.v1.PodReadinessGate Ready k8s type
```
