### ISSUE TITLE
Implement serviceAccountSpec

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#108]
as part of https://github.com/aenix-io/etcd-operator/issues/109

```yaml
serviceAccount: # TBD. How to represent it? Do we need ability to specify existing service account?
  create: true
  metadata:
    labels:
      env: prod
    annotations:
      example.com/annotation: "true"
```
