### ISSUE TITLE
Add the ability to specify volumes and containers

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#113]
As part of #109

`containers` and `volumes` specified in a `template` should be merged using strategic merge patch, for example:

```yaml
apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test
  namespace: default
spec:
  replicas: 3
  options: # map[string]string
    arg1: "value1"
    arg2: "value2"
  podTemplate:
    spec:
      containers: # []v1.Container
      - name: etcd
        volumeMounts:
        - name: test
          mountPath: /data/demo
      - name: exporter
        image: alpine
        args:
        - sleep
        - infinity
        volumeMounts:
        - name: test
          mountPath: /data/demo
      volumes: # []v1.Volume
      - name: test
        emptyDir: {}
```

should create a Pod with two containers: `etcd` and `exporter` and the same volume shared between them
