### ISSUE TITLE
Add serviceTemplate

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#115]
as part of https://github.com/aenix-io/etcd-operator/issues/109

```yaml
  serviceTemplate:
    metadata:
      labels:
        env: prod
      annotations:
        example.com/annotation: "true"
    spec: # core.v1.ServiceSpec Ready k8s type
```
