### ISSUE TITLE
Kamaji requires the single CA for server and client certificate

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#162]
etcd-operator v0.1.0

I tried to install etcd cluster using this example file https://github.com/aenix-io/etcd-operator/blob/34a4a3462a305975b0e7ea5d3ed0a73d75934b86/examples/manifests/etcdcluster-with-external-certificates.yaml

```yaml
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: default
spec:
  driver: etcd
  endpoints:
  - test-0.test.default.svc:2379
  - test-1.test.default.svc:2379
  - test-2.test.default.svc:2379
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: ca-server-secret
          namespace: default
      privateKey:
        secretReference:
          keyPath: tls.key
          name: ca-server-secret
          namespace: default
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: client-secret
          namespace: default
      privateKey:
        secretReference:
          keyPath: tls.key
          name: client-secret
          namespace: default
```

And KamajiControlPlane:

```yaml
---
# Source: kubernetes/templates/cluster.yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: test4
  namespace: tenant-foo
  labels:
    cluster.x-k8s.io/role: control-plane
  annotations:
    kamaji.clastix.io/kubeconfig-secret-key: "super-admin.svc"
spec:
  dataStoreName: "default"
  addons:
    coreDNS: {}
    konnectivity: {}
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
    - InternalIP
    - ExternalIP
  network:
    serviceType: ClusterIP
    ingress:
      extraAnnotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      hostname: test4.foo.example.org:443
      className: "tenant-root"
  deployment:
  replicas: 2
  version: 1.29.0
```

Now I see that it is trying to create control-plane pods, which get stuck on the folowing errors:

```
W0411 15:49:10.650992       1 logging.go:59] [core] [Channel #9 SubChannel #12] grpc: addrConn.createTransport failed to connect to {Addr: "test-2.test.default.svc:2379", ServerName: "test-2.test.default.svc:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
W0411 15:49:10.786047       1 logging.go:59] [core] [Channel #9 SubChannel #11] grpc: addrConn.createTransport failed to connect to {Addr: "test-1.test.default.svc:2379", ServerName: "test-1.test.default.svc:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
W0411 15:49:11.231520       1 logging.go:59] [core] [Channel #2 SubChannel #5] grpc: addrConn.createTransport failed to connect to {Addr: "test-1.test.default.svc:2379", ServerName: "test-1.test.default.svc:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
W0411 15:49:11.556638       1 logging.go:59] [core] [Channel #1 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "test-0.test.default.svc:2379", ServerName: "test-0.test.default.svc:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
W0411 15:49:12.305810       1 logging.go:59] [core] [Channel #9 SubChannel #10] grpc: addrConn.createTransport failed to connect to {Addr: "test-0.test.default.svc:2379", ServerName: "test-0.test.default.svc:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
W0411 15:49:13.253702       1 logging.go:59] [core] [Channel #2 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "test-2.test.default.svc:2379", ServerName: "test-2.test.default.svc:2379", }. Err: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
```

"remote error: tls: bad certificate" indicates that the connecting client can't validate the server's certificate

**Comment by Kirill-Garbar** [comment]
Tested in my environment. It works fine.
<img width="1103" alt="image" src="https://github.com/aenix-io/etcd-operator/assets/41306070/a8086219-aee8-4271-98f0-0676e4ec06d8">

**Comment by kvaps** [comment]
It seems Kamaji requires CA for server and CA for client to be the same file.

This way it works:

```yaml
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: default
spec:
  driver: etcd
  endpoints:
  - test-0.test.default.svc:2379
  - test-1.test.default.svc:2379
  - test-2.test.default.svc:2379
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: ca-secret
          namespace: default
      privateKey:
        secretReference:
          keyPath: tls.key
          name: ca-secret
          namespace: default
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: client-secret
          namespace: default
      privateKey:
        secretReference:
          keyPath: tls.key
          name: client-secret
          namespace: default
```

Etcd and certs:
```yaml
---
apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test
  namespace: default
spec:
  storage: {}
  security:
    tls:
      peerTrustedCASecret: ca-peer-secret
      peerSecret: peer-secret
      serverSecret: server-secret
      clientTrustedCASecret: ca-secret
      clientSecret: client-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate-peer
  namespace: default
spec:
  isCA: true
  usages:
  - "signing"
  - "key encipherment"
  - "cert sign"
  commonName: ca-peer
  subject:
    organizations:
      - ACME Inc.
    organizationalUnits:
      - Widgets
  secretName: ca-peer-secret
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: default
spec:
  isCA: true
  usages:
  - "signing"
  - "key encipherment"
  - "cert sign"
  commonName: ca
  subject:
    organizations:
      - ACME Inc.
    organizationalUnits:
      - Widgets
  secretName: ca-secret
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer-peer
  namespace: default
spec:
  ca:
    secretName: ca-peer-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: default
spec:
  ca:
    secretName: ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-certificate
  namespace: default
spec:
  secretName: server-secret
  isCA: false
  usages:
    - server auth
    - signing
    - key encipherment
  dnsNames:
  - test-0
  - test-0.test
  - test-0.test.default.svc
  - test-0.test.default.svc.cluster.local
  - test-1
  - test-1.test
  - test-1.test.default.svc
  - test-1.test.default.svc.cluster.local
  - test-2
  - test-2.test
  - test-2.test.default.svc
  - test-2.test.default.svc.cluster.local
  - test-client
  - test-client.default.svc
  - test-client.default.svc.cluster.local
  - localhost
  - "127.0.0.1"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  issuerRef:
    name: ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: peer-certificate
  namespace: default
spec:
  secretName: peer-secret
  isCA: false
  usages:
    - server auth
    - client auth
    - signing
    - key encipherment
  dnsNames:
  - test-0
  - test-0.test
  - test-0.test.default.svc
  - test-0.test.default.svc.cluster.local
  - test-1
  - test-1.test
  - test-1.test.default.svc
  - test-1.test.default.svc.cluster.local
  - test-2
  - test-2.test
  - test-2.test.default.svc
  - test-2.test.default.svc.cluster.local
  - localhost
  - "127.0.0.1"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  issuerRef:
    name: ca-issuer-peer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-certificate
  namespace: default
spec:
  commonName: root
  secretName: client-secret
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  issuerRef:
    name: ca-issuer
    kind: Issuer
```
