### ISSUE TITLE
Enable resize operation

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#210]
**phase1:**

if .spec.storage.volumeClaimTemplate.spec.resources.requestes.storage updated:

```
  storage:
    volumeClaimTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
```

then delete statefulset with `--cascade=orphan` and create a new one

**phase2:**

Loop over all PVCs

if storageClass has `allowVolumeExpansion: true`

then patch PVC object to higher size
```
spec:
  resources:
    requests:
      storage: 20Gi
```
