### ISSUE TITLE
Automatically set `quota-backend-bytes` option to 95% from requested size:

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#211]
eg.:
```
spec:
  storage:
    volumeClaimTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
```

should also implicitly set:

```
spec:
  options:
    quota-backend-bytes: "20401094656"
```

also we have to check if this option not applied by user explicitly
