### ISSUE TITLE
[epic] Secure communication with x509 certificates 

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#76]
Secure communication between etcd members and etcd clients with x509 certificates.

This is a last task remained before we start using etcd-operator in our [cozystack](https://cozystack.io) platform.

- [ ] https://github.com/aenix-io/etcd-operator/pull/125

**Comment by kvaps** [comment]
@gecube could you please elaborate on this, and write user stories and user spec for certificates

**Comment by kvaps** [comment]
link https://github.com/aenix-io/etcd-operator/pull/87/files

**Comment by Kirill-Garbar** [comment]
For now it was decided to create secret reference sections in the etcdCluster spec and expect secrets with certificates from the user of etcd-operator.

Basic spec from @lllamnyp 
```
spec:
  security:
    serverTLSSecretRef: # secretRef
      name: server-tls-secret
    clientCertAuth: true # bool
    trustedCAFile: # secretRef
      name: trusted-tls-secret
    peerTLSSecretRef: # secretRef
      name: peer-tls-secret
    peerClientCertAuth: true # bool
```

FYI @kvaps

**Comment by Kirill-Garbar** [comment]
### Peer.ca
| Option | Description |
| ------ | ----------- |
| secretName  | Secret name of user-provided secret. If not specified then operator generates certificate by the spec below |
| metadata    | Metadata of generated secret. |
| duration    | Expiration time of generated secret. |
| renewBefore | Time period before expiration time when certificate will be reissued. |
| privateKey  | Private key configuration: algorithm and key size. |

### Peer.cert
| Option | Description |
| ------ | ----------- |
| secretName  | Secret name of user-provided secret. If not specified then operator generates certificate by the spec below. If peer.ca.secretName is provided, then this certificate is generated from the CA that was provided by the user. You can't define the secret name in this section and do not define peer.ca.secretName. |
| metadata    | Metadata of generated secret. |
| duration    | Expiration time of generated secret. |
| renewBefore | Time period before expiration time when certificate will be reissued. |
| privateKey  | Private key configuration: algorithm, key size and boolean parameter is it necessary to refresh private key when certificate is expired  |

### ClientServer section has the same fields as peer section.

### Rbac
| Option | Description |
| ------ | ----------- |
| enabled  | Enables role-based access control: creates root user in etcd, gives him root role and enables authentication in etcd. |

```
spec:
  security:
      peer:
        enabled: true # optional
        ca:
          # if not defined, then operator generates CA by the spec below
          secretName: peer-ca-tls-secret
          metadata:
            annotations: {} # optional
            labels: {} # optional
          duration: 86400h # optional
          renewBefore: 720h # optional
          privateKey:
            algorithm: RSA # optional
            size: 4096 # optional
        cert:
          secretName: peer-tls-secret
          metadata:
            annotations: {}
            labels: {}
          duration: 720h
          renewBefore: 180h
          privateKey:
            reissue: true # optional
            algorithm: RSA
            size: 4096
      clientServer:
        enabled: true
        ca:
          secretName: server-ca-tls-secret
          metadata:
            annotations: {}
            labels: {}
          duration: 86400h
          renewBefore: 720h
          privateKey:
            algorithm: RSA
            size: 4096
        cert:
          secretName: server-tls-secret
          metadata:
            annotations: {}
            labels: {}
          duration: 720h
          renewBefore: 180h
          privateKey:
            reissue: true
            algorithm: RSA
            size: 4096
        rootClientCert:
          secret:
            name: client-tls-secret
            certSection: tls.crt
            keySection: tls.key
          metadata:
            annotations: {}
            labels: {}
          duration: 720h
          renewBefore: 180h
          privateKey:
            reissue: true
            algorithm: RSA
            size: 4096
        rbac:
          enabled: true # optional
```

Important points:
* If field has a value and it is optional, then this value is a default.
* peer:
  * If ca.secretName is not defined, operator generates its own CA.
  * If ca.secretName is defined, then every field under secretName should not be defined.
  * If cert.secretName id not defined, then certificate is generate by operator from the CA defined in the section above (user-managed or operator-managed).
  * User must define ca.secretName if cert.secretName is defined.
  * Algorithm is a list of the values. NOTE: look into the lib that generates certs what values exist (or to cert-manager).
* clientServer:
  * See peer logic.
  * RootClientCert uses server ca and has the same logic as server.cert.
  * Rbac.enabled enables role-based access control: creates root user in etcd, gives him root role and enables authentication in etcd.

**Comment by kvaps** [comment]
I would suggest to reuse logic of resource templates we introduced before, eg for specific resources configuration:

```
secretTemplate:
  metadata:
    name: ""
    annotations: {}
    labels: {}
```

**Comment by kvaps** [comment]
Also I'd like to ask if we really need to mount CA secret to the etcd container s?

**Comment by gecube** [comment]
@kvaps We discussed it with @Kirill-Garbar and there is no obvious reason to do it. As `ca.crt` is already present in peer and server certificate secrets. And it's authenticity is guaranteed by `cert-manager`

**Comment by Kirill-Garbar** [comment]
Ofcourse I do not want to mount CA secret to etcd container - it is not necessary.

**Comment by kvaps** [comment]
I don't like `spec.security.clientServer`, I think `spec.security.client` would be more correct. As there are always certa for `peer` and `client` communication

**Comment by Kirill-Garbar** [comment]
Client-to-server communication is written in etcd security documents: https://etcd.io/docs/v3.5/op-guide/security/
Took it from there.

In this section root client and etcd server certificates are defined.

**Comment by kvaps** [comment]
> @kvaps We discussed it with @Kirill-Garbar and there is no obvious reason to do it. As ca.crt is already present in peer and server certificate secrets. And it's authenticity is guaranteed by cert-manager

Yeah, and I like this. It is guaranteed by cert-manager but not guaranteed by `kubernetes.io/tls` secret type, just be aware and keep this in mind.

**Comment by Kirill-Garbar** [comment]
I do not want to make CA and CERTificate one secret despite the fact that certificate secret has CA.crt in one of the sections. It can be intermediate CA. And also it is not secure - if certificate secret is hijacked, then BAD ACTOR can place its own CA and etcd will automatically trust it.

But I agree that in operator functionality CA secret (that is mounted to etcd) should not include ca.key.

**Comment by kvaps** [comment]
What is the difference between `clientServer.rootClientCert` and `clientServer.cert`?

Also option `clientServer.rbac=true` is not obvious to me. From my point of view there is should be just one client certificate with root access to the cluster.

**Comment by gecube** [comment]
>  if certificate secret is hijacked, then BAD ACTOR can place its own CA and etcd will automatically trust it.

I don't agree as if hi-jacker has the access to the secrets with the certificates and private keys, the game is over already.

**Comment by Kirill-Garbar** [comment]
ClientServer cert is server certificate.
RootClientCert is certificate for the root user. Even if RBAC is not enabled, user needs client certificate.

**Comment by gecube** [comment]
> Also option clientServer.rbac=true is not obvious to me. From my point of view there is should be just one client certificate with root access to the cluster.

I may guess that it is for different use-cases, like patroni etc.

**Comment by Kirill-Garbar** [comment]
> > if certificate secret is hijacked, then BAD ACTOR can place its own CA and etcd will automatically trust it.
> 
> I don't agree as if hi-jacker has the access to the secrets with the certificates and private keys, the game is over already.

You can't remove one security layer, because you have another security layers. Security layers are independent. It is not an argument.

**Comment by kvaps** [comment]
> I do not want to make CA and CERTificate one secret despite the fact that certificate secret has CA.crt in one of the sections. It is not secure - if certificate secret is hijacked, then BAD ACTOR can place its own CA and etcd will automatically trust it.

It's okay, client certificates usually contain CA certificate but not contain CA secret. Just keep in mind that it is introduced by cert-manager and not required by `kubernetes.io/tls` secret type.

**Comment by gecube** [comment]
>  Just keep in mind that it is introduced by cert-manager and not required by kubernetes.io/tls secret type.

agree, it's a good remark, but it could be a part of our "API" or "convention"

**Comment by kvaps** [comment]
> ClientServer cert is server certificate.
RootClientCert is certificate for the root user. Even if RBAC is not enabled, user needs client certificate.

Ah got it! I would like to move this into the same level then, eg:

```
security:
  peerCertificate: {}
  peerTrustedCACertficate: {}
  clientCertificate: {}
  serverCertificate: {}
  trustedCACertificate: {}
```

As this would make it closer to repeat etcd configuration keys.

**Comment by Kirill-Garbar** [comment]
I personally like nesting structures more as usually hierarchical structure shows relations. But I do not have an argument against "closer to etcd keys". Semantically closer to etcd is important.

**Comment by kvaps** [comment]
Cool! Let's now add there
```
secretTemplate: {}
```
If it's specified, it means our operator manages secrets

Similarly to volumeClaimTemplate in STS or podDisruptionBudgetTemplate logic we have

**Comment by Kirill-Garbar** [comment]
> If it's specified, it means our operator manages secrets

I would say that operator should manage secrets by default without any additional configurations. So I would base this decision (manage by operator or attach external ones) on another field: `secretName` or we can call it `externalSecretName`. If it is defined, then do not generate own certs.

**Comment by kvaps** [comment]
I would suggest:

1) To make `secretTemplate` and `secretName` mutually exclusive. It's not allowed to have both options defined simultaneously.
2) If `secretName` specified then use external `secretName`
3) If `secretName` not specified then use automaic certificate generation from `secretTemplate`
4) let's remove `.metadata.name` from secretTemplate. I don't see the cases where user would need to override the name for the secrets.

In this way, to enable automatic certificate managedement user would need to add simple:

```yaml
---
apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test
  namespace: default
spec:
  replicas: 3
  security: {}
```

**Comment by kvaps** [comment]
Another option is that we can introduce `tls` option and place all the certs under it:

```yaml
security:
  clientAuth: true
  clientTLS: true
  tls:
    peer:
      secretName: ""
      secretTemplate: {}
    peerCA:
      secretName: ""
      secretTemplate: {}
    ca:
      secretName: ""
      secretTemplate: {}
    client:
      secretName: ""
      secretTemplate: {}
    server:
      secretName: ""
      secretTemplate: {}
      extraSANs: []
```
